window.CBE_FOODS=(window.CBE_FOODS||[]).concat([
['Apple','🍎','strong','Strong fit','Tree fruit','Fruit is harvested while the tree remains alive.','Malus domestica'],
['Pear','🍐','strong','Strong fit','Tree fruit','Fruit can be removed without ending the tree.','Pyrus communis'],
['Peach','🍑','strong','Strong fit','Tree fruit','The tree continues living after fruit harvest.','Prunus persica'],
['Nectarine','🍑','strong','Strong fit','Tree fruit','Harvesting the fruit does not end the tree.','Prunus persica'],
['Plum','🟣','strong','Strong fit','Tree fruit','The parent tree continues after harvest.','Prunus domestica'],
['Cherry','🍒','strong','Strong fit','Tree fruit','Fruit harvest leaves the tree alive.','Prunus spp.'],
['Apricot','🟠','strong','Strong fit','Tree fruit','Fruit is taken while the tree continues living.','Prunus armeniaca'],
['Orange','🍊','strong','Strong fit','Citrus fruit','Fruit is harvested without killing the tree.','Citrus sinensis'],
['Mandarin','🍊','strong','Strong fit','Citrus fruit','The producing tree remains alive after harvest.','Citrus reticulata'],
['Lemon','🍋','strong','Strong fit','Citrus fruit','Fruit removal does not end the tree.','Citrus limon'],
['Lime','🟢','strong','Strong fit','Citrus fruit','Fruit removal does not end the tree.','Citrus spp.'],
['Grapefruit','🍊','strong','Strong fit','Citrus fruit','The tree survives fruit harvest.','Citrus × paradisi'],
['Avocado','🥑','strong','Strong fit','Tree fruit','The fruit can be harvested while the tree continues living.','Persea americana'],
['Mango','🥭','strong','Strong fit','Tree fruit','The parent tree remains alive after fruit harvest.','Mangifera indica'],
['Fig','🟣','strong','Strong fit','Tree/shrub fruit','Fruit harvest does not require ending the plant.','Ficus carica'],
['Pomegranate','🔴','strong','Strong fit','Tree/shrub fruit','Fruit is removed while the woody plant remains alive.','Punica granatum'],
['Olive','🫒','strong','Strong fit','Tree fruit','Olives can be harvested repeatedly from a long-lived tree.','Olea europaea'],
['Persimmon','🟠','strong','Strong fit','Tree fruit','Fruit can be taken without ending the tree.','Diospyros kaki'],
['Coconut','🥥','strong','Strong fit','Palm fruit','The palm continues living after mature coconuts are harvested.','Cocos nucifera'],
['Grape','🍇','strong','Strong fit','Vine fruit','Grape clusters are harvested while the perennial vine survives.','Vitis vinifera'],
['Blueberry','🫐','strong','Strong fit','Berry','Berries are picked from a perennial shrub that continues living.','Vaccinium spp.'],
['Strawberry','🍓','strong','Strong fit','Berry','Fruit can be picked while the crown and runners remain alive.','Fragaria × ananassa'],
['Raspberry','🫐','strong','Strong fit','Cane fruit','Fruit is harvested without killing the perennial root system.','Rubus idaeus'],
['Blackberry','🫐','strong','Strong fit','Cane fruit','Fruit removal does not end the perennial plant.','Rubus spp.'],
['Currant','🔴','strong','Strong fit','Berry','The shrub survives fruit harvest.','Ribes spp.'],
['Gooseberry','🟢','strong','Strong fit','Berry','The shrub continues living after berries are picked.','Ribes uva-crispa'],
['Kiwi','🥝','strong','Strong fit','Vine fruit','The perennial vine remains alive after fruit harvest.','Actinidia deliciosa'],
['Passionfruit','🟣','strong','Strong fit','Vine fruit','Fruit can be harvested without ending the vine.','Passiflora edulis'],
['Tomato','🍅','strong','Strong fit','Fruiting vegetable','Picking ripe fruit does not by itself kill the plant.','Solanum lycopersicum'],
['Bell pepper','🫑','strong','Strong fit','Fruiting vegetable','Fruit can be picked repeatedly while the plant remains alive.','Capsicum annuum'],
['Chili pepper','🌶️','strong','Strong fit','Fruiting vegetable','The plant can continue producing after peppers are picked.','Capsicum spp.'],
['Cucumber','🥒','strong','Strong fit','Fruiting vegetable','Cucumbers are fruits; harvesting them does not require killing the vine.','Cucumis sativus'],
['Zucchini','🥒','strong','Strong fit','Fruiting vegetable','The fruit can be harvested repeatedly while the plant continues living.','Cucurbita pepo'],
['Summer squash','🟡','strong','Strong fit','Fruiting vegetable','Fruit harvest can occur while the plant remains alive.','Cucurbita spp.'],
['Winter squash','🎃','strong','Strong fit','Fruiting vegetable','Mature fruits can be harvested without the fruit itself being the parent organism.','Cucurbita spp.'],
['Pumpkin','🎃','strong','Strong fit','Fruiting vegetable','Pumpkins are fruits; the vine need not be killed merely to remove them.','Cucurbita spp.'],
['Eggplant','🍆','strong','Strong fit','Fruiting vegetable','Fruit can be picked while the plant continues living.','Solanum melongena'],
['Okra','🌿','strong','Strong fit','Fruiting vegetable','Pods can be harvested repeatedly from the living plant.','Abelmoschus esculentus'],
['Tomatillo','🟢','strong','Strong fit','Fruiting vegetable','Fruit can be harvested while the plant remains alive.','Physalis philadelphica'],
['Kale','🥬','strong','Strong fit','Leaf harvest','Outer leaves can be taken while the plant continues growing.','Brassica oleracea var. sabellica'],
['Swiss chard','🥬','strong','Strong fit','Leaf harvest','Outer leaves and stalks can be harvested without uprooting the crown.','Beta vulgaris var. cicla'],
['Loose-leaf lettuce','🥬','strong','Strong fit','Leaf harvest','Cut-and-come-again harvesting leaves the growing point alive.','Lactuca sativa'],
['Spinach','🥬','strong','Strong fit','Leaf harvest','Individual leaves can be harvested while the plant continues, although whole-plant harvest is different.','Spinacia oleracea'],
['Arugula','🌿','strong','Strong fit','Leaf harvest','Leaves can be selectively harvested while the plant continues growing.','Eruca vesicaria'],
['Collard greens','🥬','strong','Strong fit','Leaf harvest','Outer leaves can be harvested while the stem and growing point continue.','Brassica oleracea var. viridis'],
['Mustard greens','🥬','strong','Strong fit','Leaf harvest','Selective leaf harvest can preserve the living plant.','Brassica juncea'],
['Beet greens','🥬','strong','Strong fit','Leaf harvest','Leaves can be taken without uprooting the beet root.','Beta vulgaris'],
['Asparagus','🌱','strong','Strong fit','Perennial shoot','Spears are shoots from a perennial crown that remains underground and regrows.','Asparagus officinalis'],
['Rhubarb','🌿','strong','Strong fit','Perennial stalk','Stalks can be removed while the perennial crown survives.','Rheum × hybridum'],
['Basil','🌿','strong','Strong fit','Herb','Pruning leaves and stems can encourage continued branching.','Ocimum basilicum'],
['Mint','🌿','strong','Strong fit','Herb','Leaves and stems can be harvested while the perennial rhizomes continue.','Mentha spp.'],
['Parsley','🌿','strong','Strong fit','Herb','Outer stems can be cut while the crown remains alive.','Petroselinum crispum'],
['Cilantro','🌿','strong','Strong fit','Herb','Leaves may be selectively harvested before the plant completes its annual cycle.','Coriandrum sativum'],
['Dill','🌿','strong','Strong fit','Herb','Fronds can be selectively harvested while the plant continues.','Anethum graveolens'],
['Chives','🌿','strong','Strong fit','Herb','Leaves regrow from a perennial bulb/clump after cutting.','Allium schoenoprasum'],
['Rosemary','🌿','strong','Strong fit','Herb','Stem tips can be harvested while the woody perennial lives.','Salvia rosmarinus'],
['Thyme','🌿','strong','Strong fit','Herb','Sprigs can be harvested without ending the perennial plant.','Thymus vulgaris'],
['Oregano','🌿','strong','Strong fit','Herb','Leaves and stems can be harvested while the perennial plant continues.','Origanum vulgare'],
['Sage','🌿','strong','Strong fit','Herb','Leaves can be harvested from a long-lived perennial shrub.','Salvia officinalis'],
['Lemon balm','🌿','strong','Strong fit','Herb','Leaves can be cut while the perennial plant regrows.','Melissa officinalis'],
['Maple syrup','🍁','strong','Strong fit','Tree sap','Proper tapping removes only a small portion of sap and the tree remains alive.','Acer spp.'],
['Mushroom','🍄','strong','Strong fit','Fungal fruiting body','Harvesting a mushroom generally removes a fruiting body while the larger mycelial organism remains in the substrate.','Fungi'],
['Wheat','🌾','annual','Annual fit','Grain','Fits when grain is gathered after the annual has completed its life cycle and viable seed is retained for continuation.','Triticum aestivum'],
['Rice','🍚','annual','Annual fit','Grain','Can fit when harvested at natural crop maturity and some viable grain is retained as seed.','Oryza sativa'],
['Oats','🌾','annual','Annual fit','Grain','The annual crop can be harvested at maturity with seed reserved for future planting.','Avena sativa'],
]);