window.CBE_FOODS=(window.CBE_FOODS||[]).concat([
['Brown rice','🍚','annual','Annual fit','Whole grain rice','Brown rice is mature rice seed with bran and germ retained; it fits the annual-completion rule when harvested at maturity and seed continuation is preserved.','Oryza sativa'],
['Jasmine rice','🍚','annual','Annual fit','Aromatic rice','Jasmine rice is a mature annual grain; harvesting occurs after reproductive maturity and viable seed can be retained for continuation.','Oryza sativa'],
['Basmati rice','🍚','annual','Annual fit','Aromatic rice','Basmati is mature seed from an annual rice plant and fits the completed-cycle/seed-continuation rule.','Oryza sativa'],
['Black rice','🖤','annual','Annual fit','Pigmented rice','Black rice is a pigmented mature rice grain; the annual crop completes reproduction before grain harvest.','Oryza sativa'],
['Wild rice','🌾','annual','Annual fit','Aquatic grain','Wild rice is not the same species as Asian rice; it is the mature seed of aquatic grasses in the genus Zizania and fits the annual mature-seed continuation rule.','Zizania spp.'],
['Barley','🌾','annual','Annual fit','Grain','Fits the annual-completion rule when harvested at maturity and continuation is preserved.','Hordeum vulgare'],
['Rye','🌾','annual','Annual fit','Grain','Can fit after natural maturation with some grain saved as seed.','Secale cereale'],
['Corn','🌽','annual','Annual fit','Grain/fruit','Dry mature corn can fit the annual-completion rule; sweet corn picked young is more method-dependent.','Zea mays'],
['Millet','🌾','annual','Annual fit','Grain','Mature seed can be used as food while enough is retained for continuation.','Various genera'],
['Sorghum','🌾','annual','Annual fit','Grain','Can be harvested at maturity after the annual cycle and seed saved.','Sorghum bicolor'],
['Quinoa','🌾','annual','Annual fit','Pseudograin','Seed is harvested from a mature annual; continuation can be preserved by saving viable seed.','Chenopodium quinoa'],
['Amaranth','🌾','annual','Annual fit','Pseudograin','Mature seed fits the annual-cycle rule with seed saved.','Amaranthus spp.'],
['Buckwheat','🌾','annual','Annual fit','Pseudograin','Mature seed can fit the annual-completion principle.','Fagopyrum esculentum'],
['Black beans','🫘','annual','Annual fit','Pulse','Dry beans are mature seeds from an annual plant; save viable beans for continuation.','Phaseolus vulgaris'],
['Pinto beans','🫘','annual','Annual fit','Pulse','Dry mature beans fit when the annual cycle is complete and seed is retained.','Phaseolus vulgaris'],
['Kidney beans','🫘','annual','Annual fit','Pulse','Mature dry seeds can fit with seed preservation.','Phaseolus vulgaris'],
['Navy beans','🫘','annual','Annual fit','Pulse','Mature dry beans can fit the annual-completion rule.','Phaseolus vulgaris'],
['Chickpeas','🫘','annual','Annual fit','Pulse','Dry chickpeas are mature seeds; keep viable seed for future planting.','Cicer arietinum'],
['Lentils','🫘','annual','Annual fit','Pulse','Dry lentils are mature seeds harvested after annual maturation.','Lens culinaris'],
['Split peas','🟢','annual','Annual fit','Pulse','Derived from mature dry pea seeds; continuation can be preserved by retaining unsplit viable seed.','Pisum sativum'],
['Soybeans','🫘','annual','Annual fit','Pulse','Mature dry soybeans fit the annual rule; green edamame is harvested earlier and is method-dependent.','Glycine max'],
['Mung beans','🫘','annual','Annual fit','Pulse','Mature dry beans fit when seed is also retained for continuation.','Vigna radiata'],
['Adzuki beans','🫘','annual','Annual fit','Pulse','Mature dry beans fit the annual-completion rule.','Vigna angularis'],
['Fava beans','🫘','annual','Annual fit','Pulse','Dry mature seed can fit; fresh green favas are more method-dependent.','Vicia faba'],
['Black-eyed peas','🫘','annual','Annual fit','Pulse','Mature dry seeds can fit with continuation preserved.','Vigna unguiculata'],
['Sunflower seeds','🌻','annual','Annual fit','Seed','Seeds can be eaten while a portion is retained for continuation; the annual head is harvested at maturity.','Helianthus annuus'],
['Pumpkin seeds','🎃','annual','Annual fit','Seed','Seeds come from a fruit; eating some while saving viable seed does not require ending the parent vine.','Cucurbita spp.'],
['Sesame','🌾','annual','Annual fit','Seed','Mature seeds from an annual crop fit when some seed is preserved.','Sesamum indicum'],
['Flaxseed','🌾','annual','Annual fit','Seed','Mature seed fits the annual-cycle rule with seed saved.','Linum usitatissimum'],
['Chia seeds','🌾','annual','Annual fit','Seed','Mature seeds can fit with continuation preserved.','Salvia hispanica'],
['Hemp hearts','🌾','annual','Annual fit','Seed','Hulled mature seed can fit when viable seed stock is retained.','Cannabis sativa'],
['Peanuts','🥜','annual','Annual fit','Legume seed','Peanuts are seeds of an annual legume; the plant is usually lifted at maturity. Under CBE, harvest timing and seed preservation matter.','Arachis hypogaea'],
['Almonds','🌰','annual','Annual fit','Tree seed','Removing mature nuts does not kill the tree; continuation does not require planting every nut.','Prunus dulcis'],
['Walnuts','🌰','annual','Annual fit','Tree seed','The mature tree survives nut harvest; some nuts may be saved for propagation if desired.','Juglans spp.'],
['Pecans','🌰','annual','Annual fit','Tree seed','Nut harvest does not end the long-lived tree.','Carya illinoinensis'],
['Hazelnuts','🌰','annual','Annual fit','Shrub/tree seed','The woody plant survives harvest; continuation can be preserved without every nut germinating.','Corylus spp.'],
['Pistachios','🌰','annual','Annual fit','Tree seed','Nut harvest leaves the tree alive.','Pistacia vera'],
['Chestnuts','🌰','annual','Annual fit','Tree seed','The tree survives harvest; seed continuation can be preserved.','Castanea spp.'],
['Head lettuce','🥬','conditional','Method-dependent','Whole-head leaf crop','Whole-head harvest typically removes the living plant. Outer-leaf or cut-and-come-again methods can fit better.','Lactuca sativa'],
['Romaine hearts','🥬','conditional','Method-dependent','Leaf crop','Removing the heart removes the growing point and usually ends the individual plant. Outer-leaf harvest is more CBE-aligned.','Lactuca sativa var. longifolia'],
['Bok choy','🥬','conditional','Method-dependent','Leaf crop','Whole-plant harvest ends the plant; selective outer-leaf harvest can allow continued growth.','Brassica rapa subsp. chinensis'],
['Broccoli','🥦','conditional','Method-dependent','Flower harvest','Harvesting the central head removes a developing flower structure but the plant can often survive and produce side shoots.','Brassica oleracea var. italica'],
['Cauliflower','🥦','conditional','Method-dependent','Flower harvest','Commercial harvest usually takes the sole main curd and the plant is commonly removed afterward; not automatically lethal at the moment of cutting.','Brassica oleracea var. botrytis'],
['Brussels sprouts','🥬','conditional','Method-dependent','Bud harvest','Sprouts are buds on a living stalk; they can be picked while the plant remains alive, but commercial whole-stalk harvest differs.','Brassica oleracea var. gemmifera'],
['Artichoke','🌿','conditional','Method-dependent','Flower bud','The bud can be cut while the perennial crown remains alive, but annual production systems may remove the whole plant.','Cynara cardunculus var. scolymus'],
['Scallions','🌱','conditional','Method-dependent','Allium','If only tops are cut, the base can regrow. Pulling the entire plant removes the living bulb and roots.','Allium spp.'],
['Green onions','🌱','conditional','Method-dependent','Allium','Cutting greens above the basal plate can allow regrowth; pulling the whole plant ends it.','Allium spp.'],
['Banana','🍌','conditional','Method-dependent','Perennial herb fruit','The fruiting pseudostem naturally dies after one crop, while the underground corm and pups continue. Fits well if continuity of the clump is preserved.','Musa spp.'],
['Plantain','🍌','conditional','Method-dependent','Perennial herb fruit','Like bananas, the fruiting stalk naturally finishes after fruiting while the clonal mat continues.','Musa spp.'],
['Sweet corn','🌽','conditional','Method-dependent','Immature grain','Sweet corn is harvested before the kernels fully mature as seed. The plant can continue toward senescence, but the eaten kernels cannot be saved as mature seed.','Zea mays'],
['Green beans','🫛','conditional','Method-dependent','Immature pod','Pods are harvested before seeds mature; picking does not kill the plant, but the seeds inside are intercepted before reproductive maturity.','Phaseolus vulgaris'],
['Fresh peas','🫛','conditional','Method-dependent','Immature seed','Pods are picked while the plant may continue living; some pods can be left to mature for seed.','Pisum sativum'],
['Edamame','🫛','conditional','Method-dependent','Immature soybean','Pods are harvested before full seed maturity. The plant may be cut or uprooted during harvest, so method matters.','Glycine max'],
['Microgreens','🌱','conditional','Method-dependent','Seedling crop','Harvest usually cuts a very young plant before it can continue its life cycle, so this often conflicts with the strict CBE boundary.','Various species'],
['Sprouts','🌱','conditional','Method-dependent','Seedling crop','Eating the entire germinated seedling ends that individual seedling. Under a strict CBE reading, sprouts may fall outside the boundary.','Various species'],
['Potato','🥔','conditional','Method-dependent','Tuber','The above-ground plant often naturally senesces before harvest, but the living tubers are vegetative propagules. CBE can treat them like saved seed stock only if continuation is deliberately preserved.','Solanum tuberosum'],
['Garlic','🧄','conditional','Method-dependent','Bulb','Garlic tops usually senesce before bulb harvest, but the bulb is living propagation material. Saving cloves for continuation may make it compatible with the seed-preservation rule.','Allium sativum'],
['Onion','🧅','conditional','Method-dependent','Bulb','Bulbs are usually harvested after tops fall, but onions are biennials and the bulb is the living plant body that would normally overwinter and flower later.','Allium cepa'],
['Carrot','🥕','outside','Usually outside','Root crop','The edible storage root is the living plant body. Pulling it before its biennial life cycle completes ends the individual.','Daucus carota subsp. sativus'],
['Beetroot','🟣','outside','Usually outside','Root crop','Harvest removes the living storage root and ends the plant before its normal reproductive cycle.','Beta vulgaris'],
['Radish','🔴','outside','Usually outside','Root crop','Normal harvest removes the entire living plant to eat its root.','Raphanus sativus'],
['Turnip','🟣','outside','Usually outside','Root crop','The edible root is part of the living plant; harvesting usually ends it before reproduction.','Brassica rapa subsp. rapa'],
['Parsnip','🥕','outside','Usually outside','Root crop','Root harvest removes and ends the living biennial plant.','Pastinaca sativa'],
['Rutabaga','🟣','outside','Usually outside','Root crop','Harvest normally ends the plant to obtain its swollen root.','Brassica napus var. napobrassica'],
['Sweet potato','🍠','outside','Usually outside','Storage root','Harvest requires digging the storage roots and typically ends the cultivated plant.','Ipomoea batatas'],
['Cassava','🌿','outside','Usually outside','Storage root','Harvesting the edible roots normally requires uprooting or cutting back the plant extensively.','Manihot esculenta'],
['Taro','🌿','outside','Usually outside','Corm','Harvesting the main corm usually ends that individual, though offsets can be replanted.','Colocasia esculenta'],
['Cabbage','🥬','outside','Usually outside','Whole-head crop','Normal harvest cuts the entire head and growing point, ending the main individual.','Brassica oleracea var. capitata'],
['Leek','🌱','outside','Usually outside','Whole-plant allium','Normal harvest pulls the whole plant to eat the elongated stem and leaf bases.','Allium ampeloprasum var. porrum'],
['Celery heart','🌿','outside','Usually outside','Whole-plant harvest','Harvesting the heart removes the central growing point. Outer stalk harvest can be more continuance-preserving.','Apium graveolens'],
['Nasturtium','🌺','strong','Strong fit','Edible flower','Flowers can be picked repeatedly while the living annual continues growing and blooming. Leaves and immature seed pods are also edible.','Tropaeolum majus'],
['Calendula','🌼','strong','Strong fit','Edible flower','Petals can be harvested from flowers while the plant remains alive and continues producing blooms.','Calendula officinalis'],
['Pansy / Viola','🌸','strong','Strong fit','Edible flower','Flowers can be harvested without killing the plant; only correctly identified edible Viola types should be eaten.','Viola spp.'],
['Rose petals','🌹','strong','Strong fit','Edible flower','Petals can be removed from pesticide-free edible roses while the perennial shrub remains alive.','Rosa spp.'],
['Borage flowers','💠','strong','Strong fit','Edible flower','Individual flowers can be picked while the annual plant continues growing and flowering.','Borago officinalis'],
['Lavender flowers','💜','strong','Strong fit','Edible flower / herb','Flower spikes can be selectively harvested while the perennial plant remains alive. Use culinary lavender grown for food.','Lavandula angustifolia'],
['Chamomile flowers','🌼','strong','Strong fit','Edible flower / herb','Flower heads can be harvested repeatedly while the plant continues producing blooms.','Matricaria chamomilla'],
['Chive blossoms','🟣','strong','Strong fit','Edible flower / herb','Flower heads can be harvested from the perennial clump without ending the plant.','Allium schoenoprasum'],
['Basil flowers','🌿','strong','Strong fit','Edible flower / herb','Flowering tips can be pinched and eaten while the basil plant continues branching.','Ocimum basilicum'],
['Dill flowers','🌿','strong','Strong fit','Edible flower / herb','Flower umbels can be selectively harvested while some are left to mature seed for continuation.','Anethum graveolens'],
['Squash blossoms','🌼','strong','Strong fit','Edible flower','Blossoms can be harvested while the squash vine remains alive. Harvesting male blossoms while leaving enough for pollination best preserves continuation.','Cucurbita spp.']
]);