window.CBE_NUTRITION={
"Kale":{power:1,n:["Vitamin K","Vitamin A","Vitamin C","Folate","Calcium","Manganese","Fiber"],v:4,m:2,macro:["Fiber"],why:"Exceptionally micronutrient-dense leafy green; outer-leaf harvesting can preserve the plant."},
"Bell pepper":{power:1,n:["Vitamin C","Vitamin A","Vitamin B6","Folate","Fiber"],v:4,m:0,macro:["Fiber"],why:"Especially notable for vitamin C, with additional carotenoids and folate."},
"Chili pepper":{power:1,n:["Vitamin C","Vitamin A","Vitamin B6","Potassium"],v:3,m:1,macro:[],why:"A concentrated source of vitamin C and carotenoid pigments; heat level does not determine nutrient value."},
"Spinach":{power:1,n:["Vitamin K","Vitamin A","Folate","Iron","Magnesium","Potassium","Fiber"],v:3,m:3,macro:["Fiber"],why:"Leafy-green nutrient density with folate, vitamin K and several minerals."},
"Swiss chard":{power:1,n:["Vitamin K","Vitamin A","Vitamin C","Magnesium","Potassium","Iron","Fiber"],v:3,m:3,macro:["Fiber"],why:"A mineral-rich leafy green that can be harvested leaf by leaf."},
"Collard greens":{power:1,n:["Vitamin K","Vitamin A","Vitamin C","Folate","Calcium","Fiber"],v:4,m:1,macro:["Fiber"],why:"Strong leafy-green profile, including calcium and vitamins K, A and C."},
"Broccoli":{power:1,n:["Vitamin C","Vitamin K","Folate","Fiber","Potassium"],v:3,m:1,macro:["Fiber"],why:"A nutrient-dense flower-and-stem vegetable; CBE fit depends on harvest method."},
"Asparagus":{power:1,n:["Folate","Vitamin K","Vitamin A","Vitamin C","Fiber","Potassium"],v:4,m:1,macro:["Fiber"],why:"Perennial shoots provide folate and vitamin K while the crown remains alive underground."},
"Avocado":{power:1,n:["Folate","Vitamin K","Vitamin E","Potassium","Fiber","Monounsaturated fat"],v:3,m:1,macro:["Fiber","Healthy fats"],why:"Combines fiber, potassium, folate and predominantly unsaturated fat."},
"Blueberry":{power:1,n:["Vitamin C","Vitamin K","Manganese","Fiber","Polyphenols"],v:2,m:1,macro:["Fiber"],why:"Berries provide fiber and micronutrients plus anthocyanin polyphenols."},
"Strawberry":{power:1,n:["Vitamin C","Folate","Manganese","Fiber"],v:2,m:1,macro:["Fiber"],why:"Particularly strong in vitamin C for a commonly eaten serving."},
"Raspberry":{power:1,n:["Fiber","Vitamin C","Vitamin K","Manganese"],v:2,m:1,macro:["Fiber"],why:"One of the fiber-rich berries, with vitamin C and manganese."},
"Blackberry":{power:1,n:["Fiber","Vitamin C","Vitamin K","Manganese"],v:2,m:1,macro:["Fiber"],why:"A high-fiber berry with vitamin C, vitamin K and manganese."},
"Orange":{power:1,n:["Vitamin C","Folate","Fiber","Potassium"],v:2,m:1,macro:["Fiber"],why:"Classic vitamin C source with folate, potassium and whole-fruit fiber."},
"Kiwi":{power:1,n:["Vitamin C","Vitamin K","Vitamin E","Folate","Potassium","Fiber"],v:4,m:1,macro:["Fiber"],why:"A compact fruit with a broad vitamin profile, especially vitamin C."},
"Tomato":{power:1,n:["Vitamin C","Potassium","Folate","Vitamin K","Lycopene"],v:3,m:1,macro:[],why:"Provides vitamin C and potassium plus the carotenoid lycopene."},
"Pumpkin":{power:1,n:["Vitamin A","Vitamin C","Potassium","Fiber"],v:2,m:1,macro:["Fiber"],why:"Orange-fleshed pumpkin is especially notable for provitamin-A carotenoids."},
"Lentils":{power:1,n:["Protein","Fiber","Folate","Iron","Potassium","Magnesium"],v:1,m:3,macro:["Protein","Fiber"],why:"A major CBE-compatible protein-and-fiber anchor with folate and iron."},
"Chickpeas":{power:1,n:["Protein","Fiber","Folate","Iron","Magnesium","Manganese"],v:1,m:3,macro:["Protein","Fiber"],why:"Balanced pulse with protein, fiber, folate and several minerals."},
"Black beans":{power:1,n:["Protein","Fiber","Folate","Iron","Magnesium","Potassium"],v:1,m:3,macro:["Protein","Fiber"],why:"A strong protein-and-fiber staple with folate, iron and magnesium."},
"Soybeans":{power:1,n:["Protein","Fiber","Iron","Magnesium","Potassium","Folate"],v:1,m:3,macro:["Protein","Fiber"],why:"One of the most protein-dense legumes, with substantial mineral content."},
"Quinoa":{power:1,n:["Protein","Fiber","Magnesium","Iron","Manganese","Folate"],v:1,m:3,macro:["Protein","Fiber"],why:"A pseudograin that contributes protein, fiber and several minerals."},
"Oats":{power:1,n:["Fiber","Beta-glucan","Protein","Manganese","Magnesium","Phosphorus","Thiamin"],v:1,m:3,macro:["Protein","Fiber"],why:"Whole oats combine soluble beta-glucan fiber with minerals and thiamin."},
"Chia seeds":{power:1,n:["Fiber","Omega-3 ALA","Calcium","Magnesium","Manganese","Protein"],v:0,m:3,macro:["Protein","Fiber","Omega-3"],why:"Very fiber-rich seeds with plant omega-3 ALA and several minerals."},
"Flaxseed":{power:1,n:["Omega-3 ALA","Fiber","Thiamin","Magnesium","Manganese","Protein"],v:1,m:2,macro:["Protein","Fiber","Omega-3"],why:"Ground flax is a particularly useful plant source of ALA omega-3 plus fiber."},
"Pumpkin seeds":{power:1,n:["Protein","Magnesium","Iron","Zinc","Manganese","Unsaturated fat"],v:0,m:4,macro:["Protein","Healthy fats"],why:"Mineral-dense seeds, especially useful for magnesium, iron and zinc."},
"Sunflower seeds":{power:1,n:["Vitamin E","Thiamin","Selenium","Magnesium","Protein","Unsaturated fat"],v:2,m:2,macro:["Protein","Healthy fats"],why:"Notable for vitamin E and unsaturated fat, with selenium and magnesium."},
"Almonds":{power:1,n:["Vitamin E","Magnesium","Fiber","Protein","Calcium","Unsaturated fat"],v:1,m:2,macro:["Protein","Fiber","Healthy fats"],why:"A nutrient-dense tree seed with vitamin E, magnesium, fiber and unsaturated fat."},
"Walnuts":{power:1,n:["Omega-3 ALA","Copper","Manganese","Magnesium","Protein","Unsaturated fat"],v:0,m:3,macro:["Protein","Omega-3","Healthy fats"],why:"Distinct among common nuts for meaningful plant omega-3 ALA."},
"Pistachios":{power:1,n:["Protein","Fiber","Vitamin B6","Copper","Potassium","Unsaturated fat"],v:1,m:2,macro:["Protein","Fiber","Healthy fats"],why:"Combines protein and fiber with vitamin B6, copper and unsaturated fat."},
"Sunflower seeds":{power:1,n:["Vitamin E","Thiamin","Selenium","Magnesium","Protein","Unsaturated fat"],v:2,m:2,macro:["Protein","Healthy fats"],why:"Notable for vitamin E and unsaturated fat, with selenium and magnesium."},
"Pomegranate":{power:0,n:["Vitamin C","Vitamin K","Folate","Fiber","Polyphenols"],v:3,m:0,macro:["Fiber"],why:"Whole arils contribute fiber and vitamins alongside polyphenols."},
"Grapefruit":{power:0,n:["Vitamin C","Vitamin A","Fiber","Potassium"],v:2,m:1,macro:["Fiber"],why:"Citrus fruit with vitamin C and carotenoids; grapefruit can interact with some medications."},
"Mango":{power:0,n:["Vitamin C","Vitamin A","Folate","Fiber"],v:3,m:0,macro:["Fiber"],why:"Provides vitamin C and provitamin-A carotenoids with folate."},
"Parsley":{power:0,n:["Vitamin K","Vitamin C","Vitamin A","Folate"],v:4,m:0,macro:[],why:"Very nutrient-dense by weight, although typical serving sizes are small."},
"Basil":{power:0,n:["Vitamin K","Vitamin A","Manganese"],v:2,m:1,macro:[],why:"A micronutrient-rich herb, though ordinary serving sizes are small."},
"Artichoke":{power:0,n:["Fiber","Folate","Magnesium","Potassium","Vitamin C"],v:2,m:2,macro:["Fiber"],why:"Particularly useful for fiber, with folate and minerals."},
"Mushroom":{power:0,n:["Riboflavin","Niacin","Copper","Selenium","Potassium"],v:2,m:3,macro:[],why:"Mushrooms provide several B vitamins and minerals. Vitamin D varies substantially with species and UV exposure."}
};
window.CBE_NUTRIENT_LIST=["Protein","Fiber","Omega-3 ALA","Vitamin A","Vitamin C","Vitamin E","Vitamin K","Folate","Iron","Calcium","Magnesium","Potassium","Zinc","Selenium"];
window.CBE_NUTRITION_META={
basis:"Nutrient highlights are qualitative profiles for common forms of each food, not a substitute for a Nutrition Facts label. Exact amounts vary by variety, preparation and serving size.",
powerRule:"CBE Power Food is an editorial badge for foods with an unusually broad or strategically useful nutrient profile inside CBE. It is not a regulated nutrition claim.",
sources:["USDA FoodData Central","FDA Daily Values"]
};