window.CBE_RECIPES=[
{name:'Apple-Walnut Cinnamon Oats',emoji:'🍎',time:'10 min',fit:'Strong + annual fits',desc:'Warm oats with diced apple, walnuts, chia, cinnamon, and maple syrup.',ingredients:['rolled oats','apple','walnuts','chia seeds','cinnamon','maple syrup','water or plant milk'],steps:['Cook oats until creamy.','Fold in diced apple and cinnamon.','Top with walnuts, chia, and maple syrup.']},
{name:'Tomato-Basil Quinoa Bowl',emoji:'🍅',time:'20 min',fit:'Strong + annual fits',desc:'Quinoa, tomatoes, cucumber, basil, olives, chickpeas, lemon, and olive oil.',ingredients:['quinoa','tomatoes','cucumber','basil','olives','chickpeas','lemon','olive oil'],steps:['Cook quinoa and cool slightly.','Add chopped vegetables, basil, olives, and chickpeas.','Dress with lemon and olive oil.']},
{name:'Avocado Black Bean Rice Bowl',emoji:'🥑',time:'25 min',fit:'Strong + annual fits',desc:'A filling bowl of rice, black beans, avocado, tomato, peppers, cilantro, and lime.',ingredients:['rice','black beans','avocado','tomato','bell pepper','cilantro','lime'],steps:['Cook rice and warm beans.','Layer rice, beans, chopped produce, and avocado.','Finish with lime and cilantro.']},
{name:'Berry-Chia Overnight Oats',emoji:'🫐',time:'5 min + chill',fit:'Strong + annual fits',desc:'No-cook oats with berries, chia, walnuts, and maple.',ingredients:['oats','chia seeds','blueberries or strawberries','walnuts','plant milk or water','maple syrup'],steps:['Stir oats and chia with liquid.','Refrigerate overnight.','Add berries, walnuts, and maple before eating.']},
{name:'Lentil Pepper Tomato Stew',emoji:'🫘',time:'35 min',fit:'Strong + annual fits',desc:'Lentils simmered with tomatoes, peppers, herbs, and optional quinoa.',ingredients:['lentils','tomatoes','bell peppers','scallion tops or chives','oregano','basil','quinoa optional'],steps:['Simmer lentils until nearly tender.','Add tomatoes, peppers, and herbs.','Cook until thick; serve alone or over quinoa.']},
{name:'Cucumber Chickpea Herb Salad',emoji:'🥒',time:'10 min',fit:'Strong + annual fits',desc:'Crunchy cucumber, chickpeas, tomatoes, parsley, mint, lemon, and sesame.',ingredients:['cucumber','chickpeas','tomato','parsley','mint','lemon','sesame seeds','olive oil'],steps:['Chop cucumber, tomato, parsley, and mint.','Add chickpeas and sesame.','Dress with lemon and olive oil.']},
{name:'Pumpkin-Seed Pesto Pasta',emoji:'🌿',time:'20 min',fit:'Strong + annual fits',desc:'Basil pesto made with pumpkin seeds instead of cheese, tossed with grain pasta.',ingredients:['basil','pumpkin seeds','olive oil','lemon','whole-grain pasta','optional nutritional yeast'],steps:['Blend basil, pumpkin seeds, lemon, and olive oil.','Cook pasta.','Toss together and adjust texture with pasta water.']},
{name:'Mango Quinoa Breakfast Cup',emoji:'🥭',time:'15 min',fit:'Strong + annual fits',desc:'Quinoa with mango, chia, coconut, and a little maple syrup.',ingredients:['quinoa','mango','chia seeds','coconut','maple syrup'],steps:['Cook quinoa and cool slightly.','Top with mango, chia, and coconut.','Add maple syrup to taste.']},
{name:'Stuffed Bell Peppers',emoji:'🫑',time:'45 min',fit:'Strong + annual fits',desc:'Bell peppers filled with rice, lentils, tomatoes, herbs, and chopped walnuts.',ingredients:['bell peppers','rice','lentils','tomatoes','walnuts','parsley','oregano'],steps:['Halve peppers and remove seeds; save viable seeds if desired.','Mix cooked rice, lentils, tomatoes, walnuts, and herbs.','Fill peppers and bake until tender.']},
{name:'Fig-Walnut Greens Plate',emoji:'🟣',time:'10 min',fit:'Strong fit',desc:'Fresh figs, walnuts, loose-leaf greens, cucumber, herbs, and lemon.',ingredients:['figs','walnuts','loose-leaf lettuce','cucumber','mint','lemon','olive oil'],steps:['Arrange greens and cucumber.','Add quartered figs and walnuts.','Dress with lemon, olive oil, and mint.']}
];